version: "3.8"

services:
  backend:
    image: raghavi123/backend:latest
    container_name: staging-backend
    ports:
      - "5001:5000"
    env_file:
      - .env.staging
    restart: always

  frontend:
    image: raghavi123/frontend:latest
    container_name: staging-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: always
